
name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install tools
      run: cd tests && make install_all
    - name: Build contract
      run: make all-via-docker
    - name: Run auth_rust tests
      run: cd tests/auth_rust && bash run.sh
    - name: Clean auth_rust
      run: rm -rf tests/auth_rust/target
    - name: Run auth_spawn_rust tests
      run: cd tests/auth_spawn_rust && make all
    - name: Install cardano tools
      run: cd tests/cardano_lock && make install_cardano_tools
    - name: Run cardano tests
      run: cd tests/cardano_lock && make all
    - name: Run ckb-auth-cli tests
      run: cd tools/ckb-auth-cli && cargo test

